/**
 * Auto-generated contract tests for calculator
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: pnpm generate-tests
 */

import { describe, it, expect } from "vitest";
import vitestOpenAPI from "vitest-openapi";
import app from "../../index";
import { loadOpenAPISpec } from "../helpers/load-openapi";
import { formatResponseForValidation } from "../helpers/format-response";

const openapiSpec = loadOpenAPISpec("calculator");
vitestOpenAPI(openapiSpec);

describe("calculator API Contract Tests", () => {

    it("calculateExpression satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/calculator/calculate", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/calculator/calculate", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });
});
