/**
 * Auto-generated contract tests for file-hosting
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: pnpm generate-tests
 */

import { describe, it, expect } from "vitest";
import vitestOpenAPI from "vitest-openapi";
import app from "../../index";
import { loadOpenAPISpec } from "../helpers/load-openapi";
import { formatResponseForValidation } from "../helpers/format-response";

const openapiSpec = loadOpenAPISpec("file-hosting");
vitestOpenAPI(openapiSpec);

describe("file-hosting API Contract Tests", () => {

    it("uploadFile satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/file-hosting/upload", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/file-hosting/upload", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("uploadFileFromUrl satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/file-hosting/upload-from-url", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/file-hosting/upload-from-url", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("downloadPublicFile satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/file-hosting/public/550e8400-e29b-41d4-a716-446655440000", {
            method: "GET",
        });
        expect([200, 403, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/file-hosting/public/550e8400-e29b-41d4-a716-446655440000", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("downloadPrivateFile satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/file-hosting/private/550e8400-e29b-41d4-a716-446655440000", {
            method: "GET",
        });
        expect([200, 403, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/file-hosting/private/550e8400-e29b-41d4-a716-446655440000", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("listFiles satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/file-hosting/files", {
            method: "GET",
        });
        expect([200, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/file-hosting/files", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getFileMetadata satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/file-hosting/files/550e8400-e29b-41d4-a716-446655440000", {
            method: "GET",
        });
        expect([200, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/file-hosting/files/550e8400-e29b-41d4-a716-446655440000", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getAccessLogs satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/file-hosting/access-logs/550e8400-e29b-41d4-a716-446655440000", {
            method: "GET",
        });
        expect([200, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/file-hosting/access-logs/550e8400-e29b-41d4-a716-446655440000", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });
});
