/**
 * Auto-generated contract tests for file-encryptor
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: pnpm generate-tests
 */

import { describe, it, expect } from "vitest";
import vitestOpenAPI from "vitest-openapi";
import app from "../../index";
import { loadOpenAPISpec } from "../helpers/load-openapi";
import { formatResponseForValidation } from "../helpers/format-response";

const openapiSpec = loadOpenAPISpec("file-encryptor");
vitestOpenAPI(openapiSpec);

describe("file-encryptor API Contract Tests", () => {

    it("uploadTempFile satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/file-encryptor/upload-temp", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 413, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/file-encryptor/upload-temp", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("downloadTempFile satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/file-encryptor/download-temp/temp_550e8400-e29b-41d4-a716-446655440000", {
            method: "GET",
        });
        expect([200, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/file-encryptor/download-temp/temp_550e8400-e29b-41d4-a716-446655440000", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("deleteTempFile satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/file-encryptor/temp/temp_550e8400-e29b-41d4-a716-446655440000", {
            method: "DELETE",
        });
        expect([200, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/file-encryptor/temp/temp_550e8400-e29b-41d4-a716-446655440000", "DELETE");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });
});
