/**
 * Auto-generated contract tests for home
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: pnpm generate-tests
 */

import { describe, it, expect } from "vitest";
import { toSatisfyApiSpec } from "vitest-openapi";
import app from "../../index";
import { loadOpenAPISpec } from "../helpers/load-openapi";

expect.extend({ toSatisfyApiSpec });

const openapiSpec = loadOpenAPISpec("home");

describe("home API Contract Tests", () => {

    it("getWelcomeMessage satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/home/welcome", {
            method: "GET",
        });
        expect([200, 500]).toContain(res.status);
        expect(res).toSatisfyApiSpec(openapiSpec);
    });

    it("sendChatMessage satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/home/chat", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 500]).toContain(res.status);
        expect(res).toSatisfyApiSpec(openapiSpec);
    });
});
