/**
 * Auto-generated contract tests for home
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: pnpm generate-tests
 */

import { describe, it, expect } from "vitest";
import vitestOpenAPI from "vitest-openapi";
import app from "../../index";
import { loadOpenAPISpec } from "../helpers/load-openapi";
import { formatResponseForValidation } from "../helpers/format-response";

const openapiSpec = loadOpenAPISpec("home");
vitestOpenAPI(openapiSpec);

describe("home API Contract Tests", () => {

    it("getWelcomeMessage satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/home/welcome", {
            method: "GET",
        });
        expect([200, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/home/welcome", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getConversationHistory satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/home/chat", {
            method: "GET",
        });
        expect([200, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/home/chat", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("sendChatMessage satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/home/chat", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/home/chat", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });
});
