/**
 * Auto-generated contract tests for movies-on-demand
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: pnpm generate-tests
 */

import { describe, it, expect } from "vitest";
import vitestOpenAPI from "vitest-openapi";
import app from "../../index";
import { loadOpenAPISpec } from "../helpers/load-openapi";
import { formatResponseForValidation } from "../helpers/format-response";

const openapiSpec = loadOpenAPISpec("movies-on-demand");
vitestOpenAPI(openapiSpec);

describe("movies-on-demand API Contract Tests", () => {

    it("searchMovies satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/movies-on-demand/search", {
            method: "GET",
        });
        expect([200, 400, 500, 502]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/movies-on-demand/search", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getPopularMovies satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/movies-on-demand/popular", {
            method: "GET",
        });
        expect([200, 500, 502]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/movies-on-demand/popular", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getTopMovies satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/movies-on-demand/top", {
            method: "GET",
        });
        expect([200, 500, 502]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/movies-on-demand/top", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getMovieDetails satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/movies-on-demand/movies/550", {
            method: "GET",
        });
        expect([200, 404, 500, 502]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/movies-on-demand/movies/550", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getMovieReleases satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/movies-on-demand/movies/550/releases", {
            method: "GET",
        });
        expect([200, 404, 500, 502]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/movies-on-demand/movies/550/releases", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("fetchMovie satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/movies-on-demand/movies/550/fetch", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([202, 400, 404, 500, 502]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/movies-on-demand/movies/550/fetch", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getJobStatus satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/movies-on-demand/jobs/job_abc123", {
            method: "GET",
        });
        expect([200, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/movies-on-demand/jobs/job_abc123", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("listJobs satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/movies-on-demand/jobs", {
            method: "GET",
        });
        expect([200]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/movies-on-demand/jobs", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getWatchHistory satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/movies-on-demand/history", {
            method: "GET",
        });
        expect([200, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/movies-on-demand/history", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getMovieStream satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/movies-on-demand/movies/550/stream", {
            method: "GET",
        });
        expect([200, 400, 404, 500, 502]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/movies-on-demand/movies/550/stream", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getSimilarMovies satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/movies-on-demand/movies/550/similar", {
            method: "GET",
        });
        expect([200, 404, 500, 502]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/movies-on-demand/movies/550/similar", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });
});
