/**
 * Auto-generated contract tests for osint-tool
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: pnpm generate-tests
 */

import { describe, it, expect } from "vitest";
import vitestOpenAPI from "vitest-openapi";
import app from "../../index";
import { loadOpenAPISpec } from "../helpers/load-openapi";
import { formatResponseForValidation } from "../helpers/format-response";

const openapiSpec = loadOpenAPISpec("osint-tool");
vitestOpenAPI(openapiSpec);

describe("osint-tool API Contract Tests", () => {

    it("searchUsername satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/osint-tool/username-search", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 429, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/osint-tool/username-search", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("lookupEmail satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/osint-tool/email-lookup", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 429, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/osint-tool/email-lookup", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getDomainInfo satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/osint-tool/domain-info", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 404, 429, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/osint-tool/domain-info", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("checkBreach satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/osint-tool/breach-check", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 429, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/osint-tool/breach-check", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });
});
