/**
 * Auto-generated contract tests for remote-browser
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: pnpm generate-tests
 */

import { describe, it, expect } from "vitest";
import vitestOpenAPI from "vitest-openapi";
import app from "../../index";
import { loadOpenAPISpec } from "../helpers/load-openapi";
import { formatResponseForValidation } from "../helpers/format-response";

const openapiSpec = loadOpenAPISpec("remote-browser");
vitestOpenAPI(openapiSpec);

describe("remote-browser API Contract Tests", () => {

    it("listSessions satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/remote-browser/sessions", {
            method: "GET",
        });
        expect([200, 401, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/remote-browser/sessions", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("createSession satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/remote-browser/sessions", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([201, 400, 401, 429, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/remote-browser/sessions", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getSession satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/remote-browser/sessions/550e8400-e29b-41d4-a716-446655440000", {
            method: "GET",
        });
        expect([200, 401, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/remote-browser/sessions/550e8400-e29b-41d4-a716-446655440000", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("terminateSession satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/remote-browser/sessions/550e8400-e29b-41d4-a716-446655440000", {
            method: "DELETE",
        });
        expect([200, 401, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/remote-browser/sessions/550e8400-e29b-41d4-a716-446655440000", "DELETE");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("pauseSession satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/remote-browser/sessions/550e8400-e29b-41d4-a716-446655440000/pause", {
            method: "POST",
        });
        expect([200, 400, 401, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/remote-browser/sessions/550e8400-e29b-41d4-a716-446655440000/pause", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("resumeSession satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/remote-browser/sessions/550e8400-e29b-41d4-a716-446655440000/resume", {
            method: "POST",
        });
        expect([200, 400, 401, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/remote-browser/sessions/550e8400-e29b-41d4-a716-446655440000/resume", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("captureScreenshot satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/remote-browser/sessions/550e8400-e29b-41d4-a716-446655440000/screenshot", {
            method: "POST",
        });
        expect([200, 400, 401, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/remote-browser/sessions/550e8400-e29b-41d4-a716-446655440000/screenshot", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("controlBrowser satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/remote-browser/sessions/550e8400-e29b-41d4-a716-446655440000/control", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 401, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/remote-browser/sessions/550e8400-e29b-41d4-a716-446655440000/control", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });
});
