/**
 * Auto-generated contract tests for route-comparison
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: pnpm generate-tests
 */

import { describe, it, expect } from "vitest";
import vitestOpenAPI from "vitest-openapi";
import app from "../../index";
import { loadOpenAPISpec } from "../helpers/load-openapi";
import { formatResponseForValidation } from "../helpers/format-response";

const openapiSpec = loadOpenAPISpec("route-comparison");
vitestOpenAPI(openapiSpec);

describe("route-comparison API Contract Tests", () => {

    it("compareRoutes satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/route-comparison/compare", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 404, 429, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/route-comparison/compare", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });
});
