/**
 * Auto-generated contract tests for video-call
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: pnpm generate-tests
 */

import { describe, it, expect } from "vitest";
import vitestOpenAPI from "vitest-openapi";
import app from "../../index";
import { loadOpenAPISpec } from "../helpers/load-openapi";
import { formatResponseForValidation } from "../helpers/format-response";

const openapiSpec = loadOpenAPISpec("video-call");
vitestOpenAPI(openapiSpec);

describe("video-call API Contract Tests", () => {

    it("createSession satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/video-call/session", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/video-call/session", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("generateToken satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/video-call/token", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/video-call/token", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });
});
