/**
 * Auto-generated contract tests for video-call
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: pnpm generate-tests
 */

import { describe, it, expect } from "vitest";
import vitestOpenAPI from "vitest-openapi";
import app from "../../index";
import { loadOpenAPISpec } from "../helpers/load-openapi";
import { formatResponseForValidation } from "../helpers/format-response";

const openapiSpec = loadOpenAPISpec("video-call");
vitestOpenAPI(openapiSpec);

describe("video-call API Contract Tests", () => {

    it("createSession satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/video-call/session", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/video-call/session", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getSessionDetails satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000", {
            method: "GET",
        });
        expect([200, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("endSession satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000", {
            method: "DELETE",
        });
        expect([200, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000", "DELETE");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("generateParticipantToken satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000/participant-token", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000/participant-token", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("generateControlToken satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000/control-token", {
            method: "POST",
        });
        expect([200, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000/control-token", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("muteParticipant satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000/mute", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000/mute", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("unmuteParticipant satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000/unmute", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000/unmute", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getScreenShares satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000/screen-shares", {
            method: "GET",
        });
        expect([200, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000/screen-shares", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("uploadVideoFile satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000/video-file", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 404, 413, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000/video-file", "POST");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });

    it("getVideoFiles satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000/video-files", {
            method: "GET",
        });
        expect([200, 404, 500]).toContain(res.status);
        const formattedRes = await formatResponseForValidation(res, "/api/video-call/session/session_550e8400-e29b-41d4-a716-446655440000/video-files", "GET");
        expect(formattedRes).toSatisfyApiSpec(openapiSpec);
    });
});
