/**
 * Auto-generated contract tests for whatsapp-messenger
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: pnpm generate-tests
 */

import { describe, it, expect } from "vitest";
import { toSatisfyApiSpec } from "vitest-openapi";
import app from "../../index";
import { loadOpenAPISpec } from "../helpers/load-openapi";

expect.extend({ toSatisfyApiSpec });

const openapiSpec = loadOpenAPISpec("whatsapp-messenger");

describe("whatsapp-messenger API Contract Tests", () => {

    it("sendWhatsApp satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/whatsapp-messenger/send", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 502]).toContain(res.status);
        expect(res).toSatisfyApiSpec(openapiSpec);
    });

    it("getMessages satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/whatsapp-messenger/messages", {
            method: "GET",
        });
        expect([200, 400, 500]).toContain(res.status);
        expect(res).toSatisfyApiSpec(openapiSpec);
    });

    it("getMessagesSince satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/whatsapp-messenger/messages-since", {
            method: "GET",
        });
        expect([200, 400, 500]).toContain(res.status);
        expect(res).toSatisfyApiSpec(openapiSpec);
    });

    it("getThreads satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/whatsapp-messenger/threads", {
            method: "GET",
        });
        expect([200, 500]).toContain(res.status);
        expect(res).toSatisfyApiSpec(openapiSpec);
    });

    it("getContacts satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/whatsapp-messenger/contacts", {
            method: "GET",
        });
        expect([200, 500]).toContain(res.status);
        expect(res).toSatisfyApiSpec(openapiSpec);
    });

    it("createContact satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/whatsapp-messenger/contacts", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 500]).toContain(res.status);
        expect(res).toSatisfyApiSpec(openapiSpec);
    });

    it("updateContact satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/whatsapp-messenger/contacts/550e8400-e29b-41d4-a716-446655440000", {
            method: "PATCH",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 400, 404, 500]).toContain(res.status);
        expect(res).toSatisfyApiSpec(openapiSpec);
    });

    it("receiveWebhook satisfies OpenAPI spec", async () => {
        
        const res = await app.request("/api/whatsapp-messenger/webhook", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({}),
        });
        expect([200, 403, 500]).toContain(res.status);
        expect(res).toSatisfyApiSpec(openapiSpec);
    });
});
