/**
 * Home Page Component
 * 
 * This is the main landing page of the website. It's located at the root route (/)
 * and serves as the entry point for visitors.
 * 
 * Architecture:
 * - This is a Server Component by default in Next.js App Router
 * - Server Components run on the server (or edge with Cloudflare)
 * - They can fetch data, access databases, and don't send JavaScript to the client
 * - For interactivity, use Client Components (marked with 'use client')
 * 
 * Performance:
 * - This page is statically generated by default
 * - Can be configured for SSR, ISR, or dynamic rendering as needed
 * - Images are optimized automatically via Next.js Image component
 * 
 * @see https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts
 * @see https://nextjs.org/docs/app/building-your-application/rendering/server-components
 */

import styles from "./page.module.css";

/**
 * Home Page Component
 * 
 * This component renders the main landing page. It's a Server Component,
 * which means it runs on the server (or Cloudflare Workers edge) and
 * can perform server-side operations like data fetching.
 * 
 * @returns JSX representing the home page
 */
export default function HomePage() {
  return (
    <main className={styles.main}>
      {/* Hero Section */}
      <section className={styles.hero}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <span className={styles.highlight}>Bahasadri.com</span>
        </h1>
        
        <p className={styles.description}>
          A modern website built with{" "}
          <strong>Next.js</strong> and deployed on{" "}
          <strong>Cloudflare Workers</strong>
        </p>

        {/* Feature Grid */}
        <div className={styles.features}>
          <FeatureCard
            title="Next.js 15"
            description="Latest React framework with App Router, Server Components, and more"
          />
          <FeatureCard
            title="Cloudflare Workers"
            description="Edge computing platform for global performance and scale"
          />
          <FeatureCard
            title="TypeScript"
            description="Type-safe development for better code quality and maintainability"
          />
        </div>
      </section>

      {/* Getting Started Section */}
      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Getting Started</h2>
        <div className={styles.codeBlock}>
          <code className={styles.code}>
            # Install dependencies{'\n'}
            pnpm install{'\n\n'}
            # Run development server{'\n'}
            pnpm dev{'\n\n'}
            # Preview with Cloudflare adapter{'\n'}
            pnpm preview{'\n\n'}
            # Deploy to Cloudflare{'\n'}
            pnpm deploy
          </code>
        </div>
      </section>

      {/* Architecture Section */}
      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Architecture</h2>
        <p className={styles.paragraph}>
          This project follows a structured development approach with:
        </p>
        <ul className={styles.list}>
          <li>Comprehensive documentation for every component and page</li>
          <li>Type-safe development with TypeScript</li>
          <li>Server Components for optimal performance</li>
          <li>Edge deployment on Cloudflare Workers</li>
          <li>Modern CSS with component-scoped styles</li>
        </ul>
      </section>
    </main>
  );
}

/**
 * Feature Card Component
 * 
 * A reusable component for displaying feature information.
 * This is defined within the same file for simplicity, but could
 * be extracted to a separate file for reuse across pages.
 * 
 * @param title - The feature title
 * @param description - The feature description
 */
function FeatureCard({
  title,
  description,
}: {
  title: string;
  description: string;
}) {
  return (
    <div className={styles.card}>
      <h3 className={styles.cardTitle}>{title}</h3>
      <p className={styles.cardDescription}>{description}</p>
    </div>
  );
}

