/**
 * Home Page Component - Utility Dashboard
 *
 * This is the main dashboard page that displays all available utility tools.
 * It's located at the root route (/) and serves as the entry point for the utility website.
 *
 * Architecture:
 * - This is a Server Component by default in Next.js App Router
 * - Server Components run on the server (or edge with Cloudflare)
 * - They can fetch data, access databases, and don't send JavaScript to the client
 * - For interactivity, use Client Components (marked with 'use client')
 *
 * Performance:
 * - This page is statically generated by default
 * - Can be configured for SSR, ISR, or dynamic rendering as needed
 * - Utility cards are rendered as Server Components for optimal performance
 *
 * @see [docs/ARCHITECTURE.md](../docs/ARCHITECTURE.md) - System architecture
 * @see [docs/COMPONENTS.md](../docs/COMPONENTS.md) - Component patterns
 * @see [docs/DEVELOPMENT.md](../docs/DEVELOPMENT.md) - Development guidelines
 * @see [docs/AI_AGENT_STANDARDS.md](../docs/AI_AGENT_STANDARDS.md) - AI agent standards
 * @see https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts
 * @see https://nextjs.org/docs/app/building-your-application/rendering/server-components
 */

import UtilityCard from "./components/UtilityCard/UtilityCard";
import styles from "./page.module.css";

/**
 * Utility tool definition interface
 */
interface UtilityTool {
    /** The title of the utility */
    title: string;
    /** Brief description of what the utility does */
    description: string;
    /** The route path to the utility page */
    href: string;
    /** Optional icon/emoji to display */
    icon?: string;
}

/**
 * List of available utility tools
 * This can be moved to a separate data file or fetched from an API in the future
 */
const UTILITY_TOOLS: UtilityTool[] = [
    {
        title: "SMS Commander",
        description:
            "Pipe texts through Twilio, log the evidence, and blame the universe when it breaks.",
        href: "/tools/sms-commander",
        icon: "📡",
    },
    {
        title: "Video Commander",
        description:
            "Pipe video through Cloudflare's edge network, watch the Feds squirm, and blame WebRTC when it breaks.",
        href: "/tools/video-commander",
        icon: "📹",
    },
];

/**
 * Home Page Component - Utility Dashboard
 *
 * This component renders the utility dashboard with a grid of utility cards.
 * It's a Server Component, which means it runs on the server (or Cloudflare Workers edge).
 *
 * @returns React element representing the utility dashboard
 */
export default function HomePage() {
    return (
        <main className={styles.main}>
            {/* Hero Section */}
            <section className={styles.hero}>
                <h1 className={styles.title}>
                    The <span className={styles.highlight}>Arsenal</span>
                </h1>
                <p className={styles.description}>
                    Tools forged in the depths of my ADHD-fueled coding
                    sessions. Each one is a monument to my inability to finish
                    projects and my desperate need to automate the most trivial
                    tasks. Welcome to my digital hoarding problem.
                </p>
            </section>

            {/* Utilities Grid */}
            <section className={styles.utilitiesSection}>
                {UTILITY_TOOLS.length > 0 ? (
                    <>
                        <h2 className={styles.sectionTitle}>
                            Deployed Weapons (Probably Buggy)
                        </h2>
                        <div className={styles.utilitiesGrid}>
                            {UTILITY_TOOLS.map((utility) => (
                                <UtilityCard
                                    key={utility.href}
                                    title={utility.title}
                                    description={utility.description}
                                    href={utility.href}
                                    icon={utility.icon}
                                />
                            ))}
                        </div>
                    </>
                ) : (
                    <div className={styles.emptyState}>
                        <div className={styles.emptyIcon}>🫠</div>
                        <h2 className={styles.emptyTitle}>
                            Nothing Here Yet (Classic)
                        </h2>
                        <p className={styles.emptyDescription}>
                            The arsenal is empty because I got distracted by a
                            Wikipedia rabbit hole about Byzantine architecture.
                            Or maybe I'm just lazy. Either way, this empty state
                            is more polished than most of my actual projects.
                            The irony is not lost on me.
                        </p>
                    </div>
                )}
            </section>
        </main>
    );
}
